spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/crm_db
    username: user
    password: password
  liquibase:
    contexts: dev
logging:
  level:
    org.springframework.security: DEBUG