spring:
  profiles:
    default: dev
  application:
    name: crm
server:
  port: 8080
jwt:
  secret: dGVzdFNlY3JldEtleVRoYXRJc0xvbmdFbm91Z2hGb3JIVFQ=
  expiration: 86400000
r2:
  endpoint: https://test.r2.cloudflarestorage.com
  bucket-name: test-bucket
  access-key-id: test-access-key
  secret-access-key: test-secret-key